### ISSUE TITLE
Please publish it in NPM

### ISSUE THREAD

**Issue by moczolaszlo** [yisibl/postcss-unprefix#4]
Hello!

This is an awesome plugin, but please, publish it in NPM. :)

Thank you!

**Comment by kukac7** [comment]
@moczolaszlo https://www.npmjs.com/package/postcss-unprefix :wink:

**Comment by yisibl** [comment]
@kukac7 This plugin is still a lot of problems, I hope not to release.

**Comment by kukac7** [comment]
@yisibl ok, unpublished. sorry.
